const sql = require('mssql');

module.exports = {
    bit: sql.Bit,
    bigInt: sql.BigInt,
    decimal: sql.Decimal,
    float: sql.Float,
    int: sql.Int,
    money: sql.Money,
    numeric: sql.Numeric,
    smallInt: sql.SmallInt,
    smallMoney: sql.SmallMoney,
    real: sql.Real,
    tinyInt: sql.TinyInt,
    char: sql.Char,
    nChar: sql.NChar,
    text: sql.Text,
    nText: sql.NText,
    varChar: sql.VarChar,
    nVarChar: sql.NVarChar,
    xml: sql.Xml,
    time: sql.Time,
    date: sql.Date,
    dateTime: sql.DateTime,
    dateTime2: sql.DateTime2,
    dateTimeOffset: sql.DateTimeOffset,
    smallDateTime: sql.SmallDateTime,
    uniqueIdentifier: sql.UniqueIdentifier,
    variant: sql.Variant,
    binary: sql.Binary,
    varBinary: sql.VarBinary,
    image: sql.Image,
    uDT: sql.UDT,
    geography: sql.Geography,
    geometry: sql.Geometry
}